### ISSUE TITLE
Updating Existing Jetstream Header Layout

### ISSUE THREAD

**Issue by fyroc** [ozziexsh/laravel-jetstream-react#26]
I'm wanting to pass in additional props into the Header of the Layout. I found the types, but dont fully understand how to pass the data into it from Laravel. Is there a Controller or Middleware that I need to publish?

**Comment by ozziexsh** [comment]
not too sure what you mean, can you please share a more concrete example of what you're trying to do? ideally with a code sample of your desired result

**Comment by fyroc** [comment]
> not too sure what you mean, can you please share a more concrete example of what you're trying to do? ideally with a code sample of your desired result

In AppLayout.tsx there are page props for permissions `page.props.jetstream.hasTeamFeatures`. I need to pass in my own permissions for the navigation. How do I pass in additional page props? `hasTeamFeatures` must be defined in Laravel somewhere, right?

This is what I'm trying to accomplish:

```
{page.props.jetstream.hasBillingFeatures && (
    <JetNavLink
        href={'/billing'}
        active={route().current('billing')}
    >
        Billing
    </JetNavLink>
)}
```

I see where you would define this in the types `resources/js/types.ts` but where is it being passed into inertia via Laravel?

**Comment by ozziexsh** [comment]
gotcha

if you want the data to be available on every page you will want to edit `app/Http/Middleware/HandleInertiaRequests.php` and add anything to the `share` function there

https://inertiajs.com/shared-data

otherwise if it is specific to the route then just return it as view data when you are rendering

```php
Inertia::render('Login', [ 'foobar' => 'baz' ]);
```

and since that hook returns all props on the page (both shared and view specific) you could do 

```
const page = useTypedPage();

page.props.foobar
```
