### ISSUE TITLE
Named exports

### ISSUE THREAD

**Issue by GRardB** [ozziexsh/laravel-jetstream-react#29]
Hey there!

Since the project is in TypeScript, and named exports are more idiomatic in that world, is there any possibility to get the components to be exported this way? I know Inertia pages still likely need to be default exports, but everything else could theoretically be named.

I'm happy to open a PR for this since I've converted everything in my own project. I'd love to never have to do that again if possible 😅 

Thanks!

**Comment by ozziexsh** [comment]
hey thanks for raising this - i prefer default exports for the sake of consistency and knowing what the "main" entity is in a file, and since there are no concrete advantages to named vs default exports i'm going to leave it as is

this repo is set up in a way that you can fork it and easily make any modifications you want to support your own desires/needs though, see the "building locally" section of the readme to set this up for yourself :) 

https://github.com/ozziexsh/laravel-jetstream-react#building-locally
