### ISSUE TITLE
Could not load /resources/js/Domains/API/APITokenManager

### ISSUE THREAD

**Issue by gustaveckt** [ozziexsh/laravel-jetstream-react#36]
Hello i have installed the version 0.5.0 of laravel-jetstream-react in fresh Laravel 10.10 application. But i am facing this problem 

`[vite:load-fallback] Could not load /resources/js/Domains/API/APITokenManager (imported by resources/js/Pages/API/Index.tsx): ENOENT: no such file or directory, open '/resources/js/Domains/API/APITokenManager'
error during build:
Error: Could not load /resources/js/Domains/API/APITokenManager (imported by resources/js/Pages/API/Index.tsx): ENOENT: no such file or directory, open '/resources/js/Domains/API/APITokenManager'`. 

Can anyone help please , Tnahks.

**Comment by ozziexsh** [comment]
hey - the `Domains` folder hasn't been used since the last version, the import now matches the official laravel vue folder structure:

https://github.com/ozziexsh/laravel-jetstream-react/blob/v0.5.1/src/stubs/resources/js/Pages/API/Index.tsx#L2

there should be no error about a domains folder if you are using the latest installer version

can you please try running the command on a fresh project again, ensuring you are using the `@latest` tag

```
npx laravel-jetstream-react@latest install
```

**Comment by ozziexsh** [comment]
going to close this for now

please feel free to reopen or make a new issue if you are still having this problem
